export enum PermissionEnum {
  EDIT_USERS = 'EDIT_USERS',
  EDIT_ROLES = 'EDIT_ROLES',
  EDIT_POSTS = 'EDIT_POSTS',
  CREATE_MAINCATEGORY = 'CREATE_MEAINCATEGORY',
  CREATE_ALTCATEGORY = 'CREATE_ALTCATEGORY',
  CLOSE_POSTS = 'CLOSE_POSTS',
  CREATE_POST = 'CREATE_POST',
  CREATE_ROLE = 'CREATE_ROLE',
  EDIT_MAINCATEGORY = 'EDIT_MAINCATEGORY',
  EDIT_ALTCATEGORY = 'EDIT_ALTCATEGORY',
  CREATE_EVENT = 'CREATE_EVENT',
  EDIT_OWNER_POST = 'EDIT_OWNER_POST',
}
